### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by gcallah** [dawidd6/action-send-mail#146]
I get an invalid URL message from GH Actions on this line:
`uses: dawidd6/action-send-mail@v3`

It's copied straight from your example... so I can't figure out what is wrong.

**Comment by dawidd6** [comment]
Some more detailed information would great...

**Comment by JJ-connect** [comment]
Appears to work for me.

Do you reliably get the same error?
Can you send any more detailed information on your workflow?

**Comment by VigoTes** [comment]
Same bug for me
Can you update the Readme with a real example of 

smtp://user:password@server:port

please?

**Comment by jasonm23** [comment]
Can anyone understand that no one knows what you don't tell them?

It seems you think people are psychic and know what SMTP service you use.

Potentially not all SMTP services will accept auth via URL as it's considered unsafe and they will prefer headers.

Suggest you try using the individual settings instead of the URL to pass auth credentials.

Also, if you do have follow-up questions, remember, provide information about your specific case, or your issue will go stale.

**Comment by dawidd6** [comment]
Will accept any PRs improving the docs on this. Thanks.
